import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ComponenteHeader from "./Header/ComponenteHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen flex flex-col bg-white">
          <ComponenteHeader />

          <main className="flex-1">{children}</main>

          <footer className="bg-zinc-900 border-t border-zinc-800">
            <div className="mx-auto max-w-7xl px-6 py-8 flex flex-col md:flex-row items-center justify-between gap-4">
              <p className="text-sm text-zinc-400">
                © {new Date().getFullYear()} — Todos los derechos reservados
              </p>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
